# Multiple Monte Carlo SSA
# [Golyandina N. Detection of signals by Monte Carlo singular spectrum analysis:
# multiple testing // Statistics and Its Interface. — 2023. — Vol. 16, no. 1. — P. 147–157.]

# Contribution of Egor Poteshkin:
# correction of liberal criteria is implemented
# projection vectors with parameter basis="ev" are from Toeplitz SSA of original time series

source("R/mcmssa.R")

# for parallel computation
library(foreach)
library(doSNOW)
library(parallel)
library(doRNG)


# 1. crtiterion is exact, no correction needed: basis="ev", L=10 or basis="t" for any L

# set/load time series f of length N

N <- 100 # time series length

set.seed(1)
f <- arima.sim(
  n = N,
  model = list(ar = 0.7),
  sd = 1,
  n.start = 1,
  start.innov = rnorm(1, sd = 1 / sqrt(1 - 0.7 ^ 2))
) + 2 * cos(2 * pi * (1:N) * 0.1)

model_est <- est.model.arima(f) # estimate AR(1) parameters of f

G <- 1000 # number of surrogates
seed <- 5 # seed for mc-ssa

set.seed(seed) # for same surrogates
# projection vectors generated by series f
m <- MonteCarloSSA(
  f,
  L = 10,
  model = model_est,
  basis = "ev",
  G = G,
  level.conf = 0.8
)

m$p.value # p-value of the criterion

plot.ci(m) # plot confidence intervals


set.seed(seed) # for same surrogates
# set frequency range for alternative to increase power of the criterion
m <- MonteCarloSSA(
  f,
  L = 10,
  model = model_est,
  basis = "ev",
  G = G,
  level.conf = 0.8,
  freq.range = c(0, 0.2)
)

plot.ci(m) # plot confidence intervals


set.seed(seed) # for same surrogates
# projection vectors as eigenvectors of autocorrelation matrix of AR(1)
m <- MonteCarloSSA(
  f,
  L = 90,
  model = model_est,
  basis = "t",
  G = G,
  level.conf = 0.8
)

plot.ci(m) # plot confidence intervals

################################################################################

# 2. criterion is liberal, correction is needed: basis="ev", L>10

load("p_values_correction.RData") # for correction
recalculate <- FALSE # recalculate correction

set.seed(seed) # for same surrogates
m <- MonteCarloSSA(
  f,
  L = 90,
  model = est.model.arima(f),
  basis = "ev",
  G = G,
  level.conf = 0.8
)

# confidence intervals are liberal (leading to false discovery)
plot.ci(m)

if (recalculate) {
  M <- 1000 # number of simulations for estimating type I error
  pb <- txtProgressBar(max = M, style = 3)
  progress <- function(n) setTxtProgressBar(pb, n)
  opts <- list(progress = progress)
  
  cores <- detectCores()
  cluster <- makeCluster(cores - 1)
  registerDoSNOW(cluster)
  registerDoRNG(seed = 1)
  p.values <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f0 <- one.channel.ts(model_est, 0)
    res <-
      MonteCarloSSA(
        f = f0,
        L = 90,
        model = model_est,
        basis = "ev",
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  stopCluster(cluster)
}

# alpha_corrected <- correction(p.values_noise)
suppressWarnings(alpha_corrected <- correction(p.values)) # TODO: warning

set.seed(seed) # for same surrogates
m.corrected <- MonteCarloSSA(
  f,
  L = 90,
  model = model_est,
  basis = "ev",
  G = G,
  level.conf = 1 - alpha_corrected(0.2) # correction
)

# confidence intervals before correction
plot.ci(m)
# confidence intervals after correction (are larger)
plot.ci(m.corrected)
