---
title: "Оценка модуляции с помощью ESPRIT"
output: html_document
---

```{r message=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 10)

library(Rssa)
library(parallel)
library(doFuture)
library(doRNG)
library(progressr)
library(here)
library(ggplot2)
library(tidyverse)
library(psych)

source(here("R", "utils.R"))
```

```{r}
est_modulation_esprit <- function(x, omega, rank) {
  s <- ssa(x, svd.method = "svd")
  pe <- parestimate(s, groups = list(1:rank))
  rates <- pe$rates[order(abs(pe$freq - omega))]
  a_est <- rates[1]
  a_est * length(x)
}

est_modulation_esprit_mc <- function(model, N, omega, C, A, rank, M = 1000, seed = 123) {
  pb <- progressor(M)
  signal <- em_harmonic(N, omega, C, A)
  set.seed(seed)
  out <- foreach (i = 1:M, .combine = "c") %dorng% {
    pb()
    x <- rnorm(N, sd = sqrt(model$sigma2)) + signal
    est_modulation_esprit(x, omega, rank)
  }
  out
}
```

```{r eval=FALSE, include=FALSE}
# Run this in R console to enable progress bar
handlers(global = TRUE)
```

```{r}
cores <- 15
# Setting up parallel computing
plan(multisession, workers = min(cores, detectCores() - 1))
registerDoFuture()
```

## Засимимость оценки $C$ от силы шума

```{r}
N <- 200
omega <- 0.1
C_moderate <- 2; C_weak <- 1; C_absent <- 0
A_moderate <- 0.3; A_weak <- 0.6175159; A_absent <- 1.109272
rank <- 50

SNR <- snr(em_harmonic(N, omega, C_moderate, A_moderate))

sigma2s <- c(1, 4, 9)
models <- lapply(sigma2s, function(sigma2) list(sigma2 = sigma2))
```

```{r, eval=FALSE, message=FALSE}
C_moderate_est <- lapply(models, function(model) est_modulation_esprit_mc(model, N, omega, C_moderate, A_moderate, rank))
C_weak_est <- lapply(models, function(model) est_modulation_esprit_mc(model, N, omega, C_weak, A_weak, rank))
C_absent_est <- lapply(models, function(model) est_modulation_esprit_mc(model, N, omega, C_absent, A_absent, rank))
```

```{r}
df_moderate <- do.call(cbind, C_moderate_est) |> as.data.frame()
colnames(df_moderate) <- paste0("sigma2 = ", sigma2s)

df_weak <- do.call(cbind, C_weak_est) |> as.data.frame()
colnames(df_weak) <- paste0("sigma2 = ", sigma2s)

df_absent <- do.call(cbind, C_absent_est) |> as.data.frame()
colnames(df_absent) <- paste0("sigma2 = ", sigma2s)
```

```{r}
df_moderate |> pivot_longer(everything(), names_to = "variable", values_to = "value") |>
  ggplot(aes(x = variable, y = value)) + geom_boxplot() + geom_hline(yintercept = C_moderate, colour = "red", linetype = 2)

df_weak |> pivot_longer(everything(), names_to = "variable", values_to = "value") |>
  ggplot(aes(x = variable, y = value)) + geom_boxplot() + geom_hline(yintercept = C_weak, colour = "red", linetype = 2)

df_absent |> pivot_longer(everything(), names_to = "variable", values_to = "value") |>
  ggplot(aes(x = variable, y = value)) + geom_boxplot() + geom_hline(yintercept = 0, colour = "red", linetype = 2)
```


## Зависимость оценки $C$ от числа элементарных компонент, подаваемых в ESPRIT

Пусть $sigma^2=1$.

```{r}
N <- 200
omega <- 0.1
C_moderate <- 2; C_weak <- 1; C_absent <- 0
A_moderate <- 0.4; A_weak <- 0.8; A_absent <- 1.45
model <- list(sigma2 = 1)

ranks <- c(2, 10, 20, 30, 40, 50)

cat("SNR =", mean(em_harmonic(N, omega, C_moderate, A_moderate)^2))
```

```{r}
C_est_moderate_ranks <- lapply(
  ranks,
  function(rank)
    est_modulation_esprit_mc(model, N, omega, C_moderate, A_moderate, rank)
)
```

```{r}
df_moderate_ranks <- do.call(cbind, C_est_moderate_ranks) |> as.data.frame()
colnames(df_moderate_ranks) <- ranks

describe(df_moderate_ranks) |> select(mean, median, sd, min, max)
```

```{r}
df_moderate_ranks |>
  pivot_longer(everything(), names_to = "rank", values_to = "C_est") |>
  mutate(rank = factor(rank, levels = ranks)) |>
  ggplot(aes(x = rank, y = C_est)) +
  geom_boxplot(outliers = FALSE) +
  geom_hline(yintercept = C_moderate, colour = "red", linetype = 2)
```

```{r}
C_est_weak_ranks <- lapply(
  ranks,
  function(rank)
    est_modulation_esprit_mc(model, N, omega, C_weak, A_weak, rank)
)
```

```{r}
df_weak_ranks <- do.call(cbind, C_est_weak_ranks) |> as.data.frame()
colnames(df_weak_ranks) <- ranks

describe(df_weak_ranks) |> select(mean, median, sd, min, max)
```

```{r}
df_weak_ranks |>
  pivot_longer(everything(), names_to = "rank", values_to = "C_est") |>
  mutate(rank = factor(rank, levels = ranks)) |>
  ggplot(aes(x = rank, y = C_est)) +
  geom_boxplot(outliers = FALSE) +
  geom_hline(yintercept = C_weak, colour = "red", linetype = 2)
```

```{r}
C_est_absent_ranks <- lapply(
  ranks,
  function(rank)
    est_modulation_esprit_mc(model, N, omega, C_absent, A_absent, rank)
)
```

```{r}
df_absent_ranks <- do.call(cbind, C_est_absent_ranks) |> as.data.frame()
colnames(df_absent_ranks) <- ranks

describe(df_absent_ranks) |> select(mean, median, sd, min, max)
```

```{r}
df_absent_ranks |>
  pivot_longer(everything(), names_to = "rank", values_to = "C_est") |>
  mutate(rank = factor(rank, levels = ranks)) |>
  ggplot(aes(x = rank, y = C_est)) +
  geom_boxplot(outliers = FALSE) +
  geom_hline(yintercept = C_absent, colour = "red", linetype = 2)
```