---
title: "Сравнение методов"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(foreach)
library(doSNOW)
library(parallel)
library(doRNG)
library(xtable)

source("../R/mc-mssa.R", chdir = TRUE)
source("test_AR1.R")
load("data/comparison.RData")
```


# Про зависимость мощности критерия от коэффициента авторегрессии и частоты сигнала
```{r}
spectral_density <- function(omega) {
    delta^2 / (1 + varphi^2 - 2 * varphi * cos(2 * pi * omega))
}

N <- 1000
varphi <- 0.7
delta <- 1
model <- list(varphi = varphi,
              delta = delta,
              N = N)
omega <- 0.25
set.seed(1)
f <- one.channel.ts(model, 0.6 * cos(2 * pi * (1:N) * omega))
m <- MonteCarloSSA(f, L = 40, D = 1, basis = "ev", kind = "ev", model = model, level.conf = 0.8)
p <- plot.ci(m) + geom_function(fun = spectral_density)
p
# ggsave("../tex/img/mcssa_spec_phi7_omega025.pdf", p, device = "pdf", width = 15, height = 8, units = "cm")
```

# Сравнение с другими критериями
```{r, include=FALSE}
N <- 128
varphi <- 0.7
delta <- 1
model <- list(varphi = varphi,
              delta = delta,
              N = N)

M <- 1000
G <- 1000
Ls <- c(10, 32, 64, 96, 115)
```

```{r eval=FALSE, include=FALSE}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_noise_mcssa <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, 0)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = model,
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_noise_mcssa[[idx]] <- result
}

stopCluster(cluster)
```

```{r eval=FALSE, include=FALSE}
omega <- 0.025
signal <- 1.5 *  cos(2 * pi * (1:N) * omega)

cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_signal_mcssa_omega0025 <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, signal)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = model,
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_signal_mcssa_omega0025[[idx]] <- result
}

stopCluster(cluster)
```

```{r eval=FALSE, warning=FALSE}
p.value.noise_wavelet <- c()
set.seed(5)
for (i in 1:M) {
  ts.ar <- one.channel.ts(model, 0)
  ts0 <- ts.ar
  p.value.noise_wavelet <- c(p.value.noise_wavelet, test.ar1.wavelet(ts0))
}
```

```{r eval=FALSE, warning=FALSE}
p.value.signal_wavelet_omega0025 <- c()
set.seed(5)
for (i in 1:M) {
  ts.ar <- one.channel.ts(model, 0)
  ts0 <- ts.ar + signal
  p.value.signal_wavelet_omega0025 <- c(p.value.signal_wavelet_omega0025, test.ar1.wavelet(ts0))
}
```

```{r eval=FALSE, include=FALSE}
p.value.noise_box <- c()
set.seed(5)
for (i in 1:M) {
  ts.ar <- one.channel.ts(model, 0)
  ts0 <- ts.ar
  p.value.noise_box <- c(p.value.noise_box, test.ar1(ts0))
}
```

```{r eval=FALSE, include=FALSE}
p.value.signal_box_omega0025 <- c()
set.seed(5)
for (i in 1:M) {
  ts.ar <- one.channel.ts(model, 0)
  ts0 <- ts.ar + signal
  p.value.signal_box_omega0025 <- c(p.value.signal_box_omega0025, test.ar1(ts0))
}
```

```{r, include=FALSE}
alphas <- 0:1000/1000
clrs <- c('black', 'red', 'green', "orange", "purple")
lwds <- c(2, 1, 1, 1, 1)

alphaI_mcssa <- lapply(p.values_noise_mcssa, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
beta_mcssa <-
  lapply(p.values_signal_mcssa_omega0025, function(pvals)
    sapply(alphas, function(a)
      mean(pvals < a)))
beta_mcssa_omega0125 <-
  lapply(p.values_signal_mcssa_omega0125, function(pvals)
    sapply(alphas, function(a)
      mean(pvals < a)))
beta_mcssa_omega0225 <-
  lapply(p.values_signal_mcssa_omega0225, function(pvals)
    sapply(alphas, function(a)
      mean(pvals < a)))

alphaI_wavelet <- sapply(alphas, function(a) mean(p.value.noise_wavelet < a))
beta_wavelet_omega0025 <- sapply(alphas, function(a) mean(p.value.signal_wavelet_omega0025 < a))
beta_wavelet_omega0125 <- sapply(alphas, function(a) mean(p.value.signal_wavelet_omega0125 < a))
beta_wavelet_omega0225 <- sapply(alphas, function(a) mean(p.value.signal_wavelet_omega0225 < a))

alphaI_box <- sapply(alphas, function(a) mean(p.value.noise_box < a))
beta_box_omega0025 <- sapply(alphas, function(a) mean(p.value.signal_box_omega0025 < a))
beta_box_omega0125 <- sapply(alphas, function(a) mean(p.value.signal_box_omega0125 < a))
beta_box_omega0225 <- sapply(alphas, function(a) mean(p.value.signal_box_omega0225 < a))
```

```{r echo=FALSE}
# pdf(file = "../tex/img/alphaI_testAR.pdf", width = 15, height = 5)
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = "significance level", ylab = 'type I error', cex.lab=1.8, cex.axis=1.8, cex.sub=1.8)
for (i in seq_along(Ls))
  lines(alphas, alphaI_mcssa[[i]], lwd = lwds[i], col = clrs[i])
lines(alphas, alphaI_box, lwd = 3, col = "darkblue")
lines(alphas, alphaI_wavelet, lwd = 3, col = "brown")
legend(
  x = "bottomright",
  c("L = 10", "L = 32", "L = 64", "L = 96", "L = 115", "box", "wavelet"),
  col = c(clrs, "darkblue", "brown"),
  lty = 1,
  lwd = c(lwds, 3, 3), cex = 1.4
)
# dev.off()
```

```{r}
# pdf(file = "../tex/img/roc_testAR_omega0025.pdf", width = 15, height = 5)
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'type I error', ylab = 'power', cex.lab=1.8, cex.axis=1.8, cex.sub=1.8)
for (i in seq_along(Ls))
  lines(alphaI_mcssa[[i]][-1], beta_mcssa_omega0125[[i]][-1], lwd = lwds[i], col = clrs[i])
lines(alphaI_box, beta_box_omega0225, lwd = 3, col = "darkblue")
lines(alphaI_wavelet, beta_wavelet_omega0125, lwd = 3, col = "brown")
legend(
  x = "bottomright",
  c("L = 10", "L = 32", "L = 64", "L = 96", "L = 115", "box", "wavelet"),
  col = c(clrs, "darkblue", "brown"),
  lty = 1,
  lwd = c(lwds, 3, 3), cex = 1.4
)
# dev.off()
```
