---
title: "Оценка параметров красного шума"
output:
  html_document:
    df_print: paged
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(foreach)
library(doSNOW)
library(parallel)
library(doRNG)

source("../R/mc-mssa.R", chdir = TRUE)
load("data/p.values_noise_estim.RData")
```

```{r}
Ls <- c(10, 20, 50, 80, 90)
delta <- 1
G <- 1000

M <- 1000
pb <- txtProgressBar(max = M, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)
```

Пусть нам известно, что данный временной ряд представляет собой реализацию красного шума, но параметры $\varphi$ и $\delta$ неизвестны, т.е.
\[
f_n = \varphi f_{n-1} + \delta\varepsilon_n,\quad n=1,\ldots,N,
\]
где $\varepsilon_n\sim N(0, 1)\; \forall n$.

1. $\varphi=0.7$, $\omega=0.075$.
```{r}
varphi <- 0.7

model <- list(varphi = varphi,
              delta = delta,
              N = N)
omega <- 0.075
A <- 1
signal <- A * cos(2 * pi * (1:N) * omega)
```

```{r, results='hide'}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_h0_phi7 <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, 0)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = model,
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_h0_phi7[[idx]] <- result
}

stopCluster(cluster)
```

```{r, results='hide'}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_h0_phi7est <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, 0)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = est.model.arima(f),
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_h0_phi7est[[idx]] <- result
}

stopCluster(cluster)
```

```{r}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_h1_phi7_omega0075 <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, signal)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = model,
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_h1_phi7_omega0075[[idx]] <- result
}

stopCluster(cluster)
```

```{r}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_h1_phi7est_omega0075 <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, signal)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = est.model.arima(f),
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_h1_phi7est_omega0075[[idx]] <- result
}

stopCluster(cluster)
```

2. $\varphi=0.3$, $\omega=0.075$.
```{r}
varphi <- 0.3

model <- list(varphi = varphi,
              delta = delta,
              N = N)
omega <- 0.075
A <- 0.7
signal <- A * cos(2 * pi * (1:N) * omega)
```

```{r, results='hide'}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_h0_phi3 <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, 0)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = model,
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_h0_phi3[[idx]] <- result
}

stopCluster(cluster)
```

```{r, results='hide'}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_h0_phi3est <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, 0)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = est.model.arima(f),
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_h0_phi3est[[idx]] <- result
}

stopCluster(cluster)
```

```{r}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_h1_phi3_omega0075 <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, signal)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = model,
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_h1_phi3_omega0075[[idx]] <- result
}

stopCluster(cluster)
```

```{r}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_h1_phi3est_omega0075 <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, signal)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = est.model.arima(f),
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_h1_phi3est_omega0075[[idx]] <- result
}

stopCluster(cluster)
```

2. $\varphi=0.7$, $\omega=0.225$.
```{r}
varphi <- 0.7

model <- list(varphi = varphi,
              delta = delta,
              N = N)
omega <- 0.225
A <- 0.4
signal <- A * cos(2 * pi * (1:N) * omega)
```

```{r}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_h1_phi7_omega0225 <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, signal)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = model,
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_h1_phi7_omega0225[[idx]] <- result
}

stopCluster(cluster)
```

```{r}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_h1_phi7est_omega0225 <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, signal)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = est.model.arima(f),
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_h1_phi7est_omega0225[[idx]] <- result
}

stopCluster(cluster)
```

```{r}
alphas <- 0:1000/1000
clrs <- c('black', 'red', 'green', "orange", "purple")
lwds <- c(2, 1, 1, 1, 1)

alphaI_phi7 <-
  lapply(p.values_h0_phi7, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
alphaI_phi7est <-
  lapply(p.values_h0_phi7est, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
beta_phi7_omega0075 <-
  lapply(p.values_h1_phi7_omega0075, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
beta_phi7est_omega0075 <-
  lapply(p.values_h1_phi7est_omega0075, function(pvals) sapply(alphas, function(a) mean(pvals < a)))

alphaI_phi3 <-
  lapply(p.values_h0_phi3, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
alphaI_phi3est <-
  lapply(p.values_h0_phi3est, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
beta_phi3_omega0075 <-
  lapply(p.values_h1_phi3_omega0075, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
beta_phi3est_omega0075 <-
  lapply(p.values_h1_phi3est_omega0075, function(pvals) sapply(alphas, function(a) mean(pvals < a)))

beta_phi7_omega0225 <- 
  lapply(p.values_h1_phi7_omega0225, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
beta_phi7est_omega0225 <-
  lapply(p.values_h1_phi7est_omega0225, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
```

```{r}
# pdf(file = "../tex/img/type1error_phi7.pdf", width = 6, height = 3.5, bg = "white")
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = "significance level", ylab = 'type I error')
for (i in seq_along(Ls))
  lines(alphas, alphaI_phi7[[i]], lwd = lwds[i], col = clrs[i])
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
# dev.off()
```

```{r}
# pdf(file = "../tex/img/type1error_phi7est.pdf", width = 6, height = 3.5, bg = "white")
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = "significance level", ylab = 'type I error')
for (i in seq_along(Ls))
  lines(alphas, alphaI_phi7est[[i]], lwd = lwds[i], col = clrs[i])
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
# dev.off()
```

```{r}
# pdf(file = "../tex/img/type1error_phi3.pdf", width = 6, height = 3.5, bg = "white")
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = "significance level", ylab = 'type I error')
for (i in seq_along(Ls))
  lines(alphas, alphaI_phi3[[i]], lwd = lwds[i], col = clrs[i])
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
# dev.off()
```

```{r}
# pdf(file = "../tex/img/type1error_phi3est.pdf", width = 6, height = 3.5, bg = "white")
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = "significance level", ylab = 'type I error')
for (i in seq_along(Ls))
  lines(alphas, alphaI_phi3est[[i]], lwd = lwds[i], col = clrs[i])
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
# dev.off()
```

```{r}
# pdf(file = "../tex/img/roc_phi7_omega0075.pdf", width = 6, height = 3.5, bg = "white")
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'type I error', ylab = 'power', xlim = c(0, 1))
for (i in seq_along(Ls)) {
  lines(alphaI_phi7[[i]][-1], beta_phi7_omega0075[[i]][-1], lwd = lwds[i], col = clrs[i])
}
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
# dev.off()
```

```{r}
# pdf(file = "../tex/img/roc_phi7est_omega0075.pdf", width = 6, height = 3.5, bg = "white")
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'type I error', ylab = 'power', xlim = c(0, 1))
for (i in seq_along(Ls)) {
  lines(alphaI_phi7est[[i]][-1], beta_phi7est_omega0075[[i]][-1], lwd = lwds[i], col = clrs[i])
}
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
# dev.off()
```

```{r}
# pdf(file = "../tex/img/roc_phi3_omega0075.pdf", width = 6, height = 3.5, bg = "white")
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'type I error', ylab = 'power', xlim = c(0, 1))
for (i in seq_along(Ls)) {
  lines(alphaI_phi3[[i]][-1], beta_phi3_omega0075[[i]][-1], lwd = lwds[i], col = clrs[i])
}
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
#dev.off()
```

```{r}
# pdf(file = "../tex/img/roc_phi3est_omega0075.pdf", width = 6, height = 3.5, bg = "white")
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'type I error', ylab = 'power', xlim = c(0, 1))
for (i in seq_along(Ls)) {
  lines(alphaI_phi3est[[i]][-1], beta_phi3est_omega0075[[i]][-1], lwd = lwds[i], col = clrs[i])
}
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
# dev.off()
```

```{r}
# pdf(file = "../tex/img/roc_phi7_omega0225.pdf", width = 15, height = 5, bg = "white")
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'type I error', ylab = 'power', xlim = c(0, 1), cex.lab=1.8, cex.axis=1.8, cex.sub=1.8)
for (i in seq_along(Ls)) {
  lines(alphaI_phi7[[i]][-1], beta_phi7_omega0225[[i]][-1], lwd = lwds[i], col = clrs[i])
}
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds, cex = 2)
# dev.off()
```

```{r}
# pdf(file = "../tex/img/roc_phi7est_omega0225.pdf", width = 15, height = 5, bg = "white")
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'type I error', ylab = 'power', xlim = c(0, 1), cex.lab=1.8, cex.axis=1.8, cex.sub=1.8)
for (i in seq_along(Ls)) {
  lines(alphaI_phi7est[[i]][-1], beta_phi7est_omega0225[[i]][-1], lwd = lwds[i], col = clrs[i])
}
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds, cex = 2)
# dev.off()
```
