---
title: "analyse one time series"
output: html_notebook
---

```{r setup, include=FALSE}
source("mcmssa_utils.R")
source("noise_estim.R")
source("auto_trend_ssa.R")
library(foreach)
library(doSNOW)
library(parallel)
library(doRNG)
```

```{r}
N <- 100
varphi <- 0.7
delta <- 1
Ls <- c(10, 20, 50, 80, 90)
G <- 1000
M <- 1000
model <- list(varphi = varphi,
              delta = delta,
              N = N)
alphas <- c(seq(0, 0.025, 0.0001), seq(0.025, 1, 0.001))
alphas_idx <- seq_along(alphas)
```

```{r}
signal.known <- 0.2 * exp(0.05 * (1:N))
omega.unknown <- 0.25
signal.unknown <- signal.one.channel(N, omega.unknown)

model.signal <- model
model.signal$signal <- signal.known
```

```{r}
# Строим скорректированные уровни значимости:
load("p_values_nuisance.RData")
L1 <- 90
L2 <- 90
ind1 <- which(Ls == L1)
ind2 <- which(Ls == L2)
alphas_corrected_trend <- correction(p.values_h0trend[[ind1]])
alphas_corrected <- correction(p.values_h0[[ind2]])
```

```{r}
seed <- Sys.time()
set.seed(seed)
noise <- one.channel.ts(model, 0)

f.trend <- signal.known + signal.unknown + noise
f <- signal.unknown + noise


# Вариант с трендом
m.trend <- MonteCarloSSA(f.trend,
                         L = L1,
                         D = 1,
                         basis = "ev",
                         kind = "ev",
                         model = model.signal,
                         G = G,
                         composite = TRUE,
                         level.conf = 1 - alphas_corrected_trend(0.2))

# Вариант без тренда
set.seed(seed)
m <- MonteCarloSSA(f,
                   L = L2,
                   D = 1,
                   basis = "ev",
                   kind = "ev",
                   model = model,
                   G = G,
                   level.conf = 1 - alphas_corrected(0.2))

# Доверительные интервалы
par(mfrow = c(1,2))
plot.ci(m.trend)
plot.ci(m)

# Значимые частоты
m.trend$freq[m.trend$v > m.trend$upper]
m$freq[m$v > m$upper]
m.trend$freq
m$freq
```

```{r}
ind <- 0
ind.trend <- 0

A <- 0

P <- 100

for(i in 1:P) {
  print(i)
  seed <- 42*i
  set.seed(seed)
  noise <- one.channel.ts(model, 0)
  f.trend <- A * signal.unknown + signal.known + noise
  f <- A * signal.unknown + noise

  # Вариант с трендом
  m.trend <- MonteCarloSSA(f.trend,
                           L = L1,
                           D = 1,
                           basis = "ev",
                           kind = "ev",
                           model = model.signal,
                           G = G,
                           composite = TRUE,
                           level.conf = 1 - alphas_corrected_trend(0.2))

  # Вариант без тренда
  set.seed(seed)
  m <- MonteCarloSSA(f,
                     L = L2,
                     D = 1,
                     basis = "ev",
                     kind = "ev",
                     model = model,
                     G = G,
                     level.conf = 1 - alphas_corrected(0.2))
  ind.trend <- ind.trend + is.element(TRUE, m.trend$v > m.trend$upper)
  ind <- ind + is.element(TRUE, m$v > m$upper)
}

ind.trend/P
ind/P
```
