---
title: "Зависимость радикальности от длины ряда"
output: html_document
---

```{r, include=FALSE}
source("mcmssa_utils.R")
library(foreach)
library(doSNOW)
library(parallel)
library(doRNG)
library(gcplyr)
load("p.values_Ns.RData")
```

Возьмем $N=100,200,500,1000$ и посмотрим на графики ошибок первого рода при разных $L$.
```{r, include=FALSE}
Ns <- c(100, 200, 500, 1000)
varphi <- 0.7
delta <- 1
model <- list(varphi = varphi,
              delta = delta)

M <- 1000
G <- 1000
alphas <- 0:1000/1000
clrs <- c('black', 'red', 'green', "orange")
lwds <- c(2, 1, 1, 1)
```

```{r eval=FALSE, include=FALSE}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_noise_L80 <- list()
for (idx in seq_along(Ns)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    model$N <- Ns[idx]
    f <- one.channel.ts(model, 0)
    res <-
      MonteCarloSSA(
        f = f,
        L = L,
        model = model,
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_noise_L80[[idx]] <- result
}

stopCluster(cluster)
```

1. $L=10$
```{r, include=FALSE}
alphaI_L10 <- lapply(p.values_noise_L10, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
```

```{r, echo=FALSE}
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'significance level', ylab = 'type I error', main = "L = 10")
for (i in seq_along(Ns))
  lines(alphas, alphaI_L10[[i]], lwd = lwds[i], col = clrs[i])
legend(x = "bottomright", as.character(Ns), col = clrs, lty = 1, lwd = lwds)
```

Ошибка первого рода при $\alpha=0.1$:
```{r, echo=FALSE}
sapply(p.values_noise_L10, function(p) mean(p < 0.1))
```

AUC:
```{r, echo=FALSE}
sapply(seq_along(Ns), function(i) auc(alphas, alphaI_L10[[i]], xlim = c(0, 1)))
```

2. $L=40$
```{r, include=FALSE}
alphaI_L40 <- lapply(p.values_noise_L40, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
```

```{r, echo=FALSE}
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'significance level', ylab = 'type I error', main = "L = 40")
for (i in seq_along(Ns))
  lines(alphas, alphaI_L40[[i]], lwd = lwds[i], col = clrs[i])
legend(x = "bottomright", as.character(Ns), col = clrs, lty = 1, lwd = lwds)
```

Ошибка первого рода при $\alpha=0.1$:
```{r echo=FALSE}
sapply(p.values_noise_L40, function(p) mean(p < 0.1))
```

AUC:
```{r, echo=FALSE}
sapply(seq_along(Ns), function(i) auc(alphas, alphaI_L40[[i]], xlim = c(0, 1)))
```

3. $L=80$
```{r, include=FALSE}
alphaI_L80 <- lapply(p.values_noise_L80, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
```

```{r, echo=FALSE}
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'significance level', ylab = 'type I error', main = "L = 80")
for (i in seq_along(Ns))
  lines(alphas, alphaI_L80[[i]], lwd = lwds[i], col = clrs[i])
legend(x = "bottomright", as.character(Ns), col = clrs, lty = 1, lwd = lwds)
```

Ошибка первого рода при $\alpha=0.1$:
```{r echo=FALSE}
sapply(p.values_noise_L80, function(p) mean(p < 0.1))
```

AUC:
```{r, echo=FALSE}
sapply(seq_along(Ns), function(i) auc(alphas, alphaI_L80[[i]], xlim = c(0, 1)))
```
