---
title: "Большая длина ряда"
output: html_document
---

```{r, include=FALSE}
source("mcmssa_utils.R")
library(foreach)
library(doSNOW)
library(parallel)
library(doRNG)
load("largeN_comparison.RData")

N <- 512
varphi <- 0.7
delta <- 1
model <- list(varphi = varphi,
              delta = delta,
              N = N)

M <- 1000
G <- 1000
Ls <- c(10, 256, 460)
```

Пусть $N=512$, $\varphi=0.7$, $\delta=1$, $\omega=0.075$.
```{r eval=FALSE, include=FALSE}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_noise_mcssa <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, 0)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = model,
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_noise_mcssa[[idx]] <- result
}

stopCluster(cluster)
```

```{r eval=FALSE, include=FALSE}
signal <- 0.5 * cos(2 * pi * (1:N) * 0.075)

cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)

p.values_signal_mcssa <- list()
for (idx in seq_along(Ls)) {
  result <- foreach (
    i = 1:M,
    .combine = 'c',
    .export = c('Norm', 'rowQuantiles'),
    .packages = "Rssa",
    .options.snow = opts
  ) %dopar% {
    f <- one.channel.ts(model, signal)
    res <-
      MonteCarloSSA(
        f = f,
        L = Ls[idx],
        model = model,
        basis = "ev",
        kind = "ev",
        D = 1,
        G = G,
        level.conf = NULL
      )
    res$p.value
  }
  p.values_signal_mcssa[[idx]] <- result
}

stopCluster(cluster)
```

```{r eval=FALSE, include=FALSE}
p.value.noise_wavelet <- c()
set.seed(5)
for (i in 1:M) {
  ts.ar <- one.channel.ts(model, 0)
  ts0 <- ts.ar
  p.value.noise_wavelet <- c(p.value.noise_wavelet, test.ar1.wavelet(ts0))
}
```

```{r eval=FALSE, include=FALSE}
p.value.signal_wavelet <- c()
set.seed(5)
for (i in 1:M) {
  ts.ar <- one.channel.ts(model, 0)
  ts0 <- ts.ar + signal
  p.value.signal_wavelet <- c(p.value.signal_wavelet, test.ar1.wavelet(ts0))
}
```

```{r eval=FALSE, include=FALSE}
p.value.noise_box <- c()
set.seed(5)
for (i in 1:M) {
  ts.ar <- one.channel.ts(model, 0)
  ts0 <- ts.ar
  p.value.noise_box <- c(p.value.noise_box, test.ar1(ts0))
}
```

```{r eval=FALSE, include=FALSE}
p.value.signal_box <- c()
set.seed(5)
for (i in 1:M) {
  ts.ar <- one.channel.ts(model, 0)
  ts0 <- ts.ar + signal
  p.value.signal_box <- c(p.value.signal_box, test.ar1(ts0))
}
```

```{r, include=FALSE}
alphas <- 0:1000/1000
clrs <- c('black', 'red', 'green')
lwds <- c(2, 1, 1)

alphaI_mcssa <- lapply(p.values_noise_mcssa, function(pvals) sapply(alphas, function(a) mean(pvals < a)))
beta_mcssa <- lapply(p.values_signal_mcssa, function(pvals) sapply(alphas, function(a) mean(pvals < a)))

alphaI_wavelet <- sapply(alphas, function(a) sum(p.value.noise_wavelet < a) / M)
beta_wavelet <- sapply(alphas, function(a) sum(p.value.signal_wavelet < a) / M)

alphaI_box <- sapply(alphas, function(a) sum(p.value.noise_box < a) / M)
beta_box <- sapply(alphas, function(a) sum(p.value.signal_box < a) / M)
```

```{r echo=FALSE}
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, xlab = 'significance level', ylab = 'type I error')
for (i in seq_along(Ls))
  lines(alphaI_mcssa[[i]], beta_mcssa[[i]], lwd = lwds[i], col = clrs[i])
lines(alphaI_wavelet, beta_wavelet, col = "orange")
lines(alphaI_box, beta_box, col = "purple")
legend(
  x = "bottomright",
  c("MC-SSA (L=10)", "MC-SSA (L=256)", "MC-SSA (L=460)", "Whitening + genwwn.test", "Whitening + Box.test"),
  col = c(clrs, "orange", "purple"),
  lty = 1,
  lwd = c(lwds, 1, 1)
)
```
