---
title: "task2"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("mcmssa_utils.R")
source("noise_estim.R")
source("auto_trend_ssa.R")
library(foreach)
library(doSNOW)
library(parallel)
library(doRNG)
```

```{r}
N <- 100
varphi <- 0.7
delta <- 1
Ls <- c(10, 20, 50, 80, 90)
D <- 1
G <- 1000
M <- 1000
model <- list(varphi = varphi,
              delta = delta,
              N = N)
```

```{r, include=FALSE}
pb <- txtProgressBar(max = M, style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)
```
Теперь пусть известно, что в ряде присутсвует тренд. Нужно проверить, есть ли еще сигнал.
```{r}
omega.unknown <- 0.075
signal.known <- 0.2 * exp(0.05 * (1:N))
signal.unknown <- signal.one.channel(N, omega.unknown)
```
Пусть тренд и параметры шума известны точно.

# Вариант тренд + шум
```{r, results='hide'}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)
p.values_h0trend <- list()
for (k in seq_along(Ls)) {
  result <- foreach (i=1:M,
                    .export=c('ssa', 'nu', 'parestimate', 'Norm', 'rowQuantiles', 'reconstruct', 'grouping.auto'),
                    .combine='cbind',
                    .options.snow=opts) %dopar%
    {
      f <- one.channel.ts(model, signal.known)
      model.signal <- model
      model.signal$signal <- signal.known
      m <- MonteCarloSSA(f = f,
                         model = model.signal,
                         L = Ls[k],
                         D = 1,
                         basis = "ev",
                         kind = "ev",
                         G = G,
                         level.conf = NULL,
                         composite = "var1")
      m$p.value
    }
  p.values_h0trend[[k]] <- result
}
stopCluster(cluster)
```

```{r, results='hide'}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)
p.values_h1trend <- list()
for (k in seq_along(Ls)) {
  result <- foreach (i=1:M,
                .export=c('ssa', 'nu', 'parestimate', 'Norm', 'rowQuantiles', 'reconstruct', 'grouping.auto'),
                .combine='cbind',
                .options.snow=opts) %dopar%
    {
      f <- one.channel.ts(model, signal.unknown + signal.known)
      model.signal <- model
      model.signal$signal <- signal.known
      m <- MonteCarloSSA(f = f,
                         model = model.signal,
                         L = Ls[k],
                         D = 1,
                         basis = "ev",
                         kind = "ev",
                         G = G,
                         level.conf = NULL,
                         composite = "var1")
      m$p.value
    }
  p.values_h0trend[[k]] <- result
}
stopCluster(cluster)
```

# Вариант без тренда
```{r, results='hide'}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)
p.values_h0 <- list()
for (k in seq_along(Ls)) {
  result <- foreach (i=1:M,
                    .export=c('ssa', 'nu', 'parestimate', 'Norm', 'rowQuantiles', 'reconstruct', 'grouping.auto'),
                    .combine='cbind',
                    .options.snow=opts) %dopar%
    {
      f <- one.channel.ts(model, 0)
      m <- MonteCarloSSA(f = f,
                         model = model,
                         L = Ls[k],
                         D = 1,
                         basis = "ev",
                         kind = "ev",
                         G = G,
                         level.conf = NULL,
                         composite = "none")
      m$p.value
    }
  p.values_h0[[k]] <- result
}
stopCluster(cluster)
```

```{r, results='hide'}
cores <- detectCores()
cluster <- makeCluster(cores - 1)
registerDoSNOW(cluster)
registerDoRNG(seed = 1, once = FALSE)
p.values_h1 <- list()
for (k in seq_along(Ls)) {
  result <- foreach (i=1:M,
                .export=c('ssa', 'nu', 'parestimate', 'Norm', 'rowQuantiles', 'reconstruct', 'grouping.auto'),
                .combine='cbind',
                .options.snow=opts) %dopar%
    {
      f <- one.channel.ts(model, signal.unknown)
      m <- MonteCarloSSA(f = f,
                         model = model,
                         L = Ls[k],
                         D = 1,
                         basis = "ev",
                         kind = "ev",
                         G = G,
                         level.conf = NULL,
                         composite = "none")
      m$p.value
    }
  p.values_h1[[k]] <- result
}
stopCluster(cluster)
```

```{r}
alphas <- c(seq(0, 0.025, 0.0001), seq(0.025, 1, 0.001))
alphas_idx <- seq_along(alphas)
clrs <- c('black', 'red', 'green', 'orange', 'purple')
lwds <- c(2, 1, 1, 1, 1)
```

```{r}
alphaI.trend <- lapply(p.values_h0trend, function(p) sapply(alphas, function(a) sum(p < a) / M))
alphaI <- lapply(p.values_h0, function(p) sapply(alphas, function(a) sum(p < a) / M))

beta.trend <- lapply(p.values_h1trend, function(p) sapply(alphas, function(a) sum(p < a) / M))
beta <- lapply(p.values_h1, function(p) sapply(alphas, function(a) sum(p < a) / M))
```

# Графики ошибок I рода, мощности и ROC-кривые
```{r}
plot(c(0,1),c(0,1), type="l", col = "blue", lty = 2, main = "Type I error", xlab = 'significance level', ylab = 'type I error')
for (i in seq_along(Ls)) {
  lines(alphas, alphaI.trend[[i]], lwd = lwds[i], col = clrs[i])
  lines(alphas, alphaI[[i]], lwd = lwds[i], lty = 2, col = clrs[i])
}
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
```
  
```{r}
plot(c(0,1),c(0,1), type="l", col="blue", lty = 2, main = "Power", xlab = 'significance level', ylab = 'power')
for (i in seq_along(Ls)) {
  lines(alphas, beta.trend[[i]], lwd = lwds[i], col = clrs[i])
  lines(alphas, beta[[i]], lty = 2, lwd = lwds[i], col = clrs[i])
}
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
```

```{r}
plot(c(0,1),c(0,1), type="l", col="blue", lty = 2, main = "ROC curve", xlab = 'type I error', ylab = 'power')
for (i in seq_along(Ls)) {
  lines(alphaI.trend.estim[[i]], beta.trend.estim[[i]], lwd = lwds[i], col = clrs[i])
  lines(alphaI[[i]], beta[[i]], lwd = lwds[i], lty = 2, col = clrs[i])
}
legend(x = "bottomright", as.character(Ls), col = clrs, lty = 1, lwd = lwds)
```
